#pragma once
#include "Amazon/DynamoDBv2/Model/Internal/MarshallTransformations/zzzz__AutoScalingTargetTrackingScalingPolicyConfigurationUpdateMarshaller_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Amazon/DynamoDBv2/Model/Internal/MarshallTransformations/zzzz__AutoScalingTargetTrackingScalingPolicyConfigurationUpdateMarshaller_impl.hpp"
#endif
