#pragma once
#include "Amazon/DynamoDBv2/Model/Internal/MarshallTransformations/zzzz__DescribeKinesisStreamingDestinationResponseUnmarshaller_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Amazon/DynamoDBv2/Model/Internal/MarshallTransformations/zzzz__DescribeKinesisStreamingDestinationResponseUnmarshaller_impl.hpp"
#endif
