#pragma once
#include "Amazon/DynamoDBv2/Model/Internal/MarshallTransformations/zzzz__EnableKinesisStreamingDestinationResponseUnmarshaller_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Amazon/DynamoDBv2/Model/Internal/MarshallTransformations/zzzz__EnableKinesisStreamingDestinationResponseUnmarshaller_impl.hpp"
#endif
