#pragma once
#include "Amazon/DynamoDBv2/Model/Internal/MarshallTransformations/zzzz__GlobalTableGlobalSecondaryIndexSettingsUpdateMarshaller_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Amazon/DynamoDBv2/Model/Internal/MarshallTransformations/zzzz__GlobalTableGlobalSecondaryIndexSettingsUpdateMarshaller_impl.hpp"
#endif
