#pragma once
#include "Amazon/DynamoDBv2/Model/Internal/MarshallTransformations/zzzz__ListGlobalTablesEndpointDiscoveryMarshaller_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Amazon/DynamoDBv2/Model/Internal/MarshallTransformations/zzzz__ListGlobalTablesEndpointDiscoveryMarshaller_impl.hpp"
#endif
