#pragma once
#include "Amazon/DynamoDBv2/Model/Internal/MarshallTransformations/zzzz__PointInTimeRecoveryUnavailableExceptionUnmarshaller_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Amazon/DynamoDBv2/Model/Internal/MarshallTransformations/zzzz__PointInTimeRecoveryUnavailableExceptionUnmarshaller_impl.hpp"
#endif
