#pragma once
#include "Amazon/DynamoDBv2/Model/Internal/MarshallTransformations/zzzz__UpdateGlobalSecondaryIndexActionMarshaller_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Amazon/DynamoDBv2/Model/Internal/MarshallTransformations/zzzz__UpdateGlobalSecondaryIndexActionMarshaller_impl.hpp"
#endif
