#ifdef __cpp_modules
module;
#endif

#pragma once
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/AppStreamActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/AutoScalingActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/BillingActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/CloudFormationActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/CloudFrontActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/CloudSearchActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/CloudTrailActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/CloudWatchActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/CloudWatchLogsActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/CognitoIdentityActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/CognitoSyncActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/DirectConnectActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/DynamoDBActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/EC2ActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/ElastiCacheActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/ElasticBeanstalkActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/ElasticLoadBalancingActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/ElasticMapReduceActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/ElasticTranscoderActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/GlacierActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/IdentityandAccessManagementActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/ImportExportActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/KinesisActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/MarketplaceActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/MarketplaceManagementPortalActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/MobileAnalyticsActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/OpsWorksActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/RDSActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/RedshiftActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/Route53ActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/S3ActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/SESActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/SNSActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/SQSActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/SecurityTokenServiceActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/SimpleDBActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/SimpleWorkflowServiceActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/StorageGatewayActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/WhispersyncActionIdentifiers.hpp"
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/ZocaloActionIdentifiers.hpp"
#ifdef __cpp_modules
export module ActionIdentifiers;
#endif
