#pragma once
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/zzzz__MarketplaceManagementPortalActionIdentifiers_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Amazon/Auth/AccessControlPolicy/ActionIdentifiers/zzzz__MarketplaceManagementPortalActionIdentifiers_impl.hpp"
#endif
