#pragma once
#include "Amazon/Lambda/Model/Internal/MarshallTransformations/zzzz__GetFunctionEventInvokeConfigRequestMarshaller_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Amazon/Lambda/Model/Internal/MarshallTransformations/zzzz__GetFunctionEventInvokeConfigRequestMarshaller_impl.hpp"
#endif
