#pragma once
#include "Amazon/Lambda/Model/Internal/MarshallTransformations/zzzz__PutProvisionedConcurrencyConfigRequestMarshaller_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Amazon/Lambda/Model/Internal/MarshallTransformations/zzzz__PutProvisionedConcurrencyConfigRequestMarshaller_impl.hpp"
#endif
