#pragma once
#include "Amazon/Lambda/Model/Internal/MarshallTransformations/zzzz__RemoveLayerVersionPermissionRequestMarshaller_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Amazon/Lambda/Model/Internal/MarshallTransformations/zzzz__RemoveLayerVersionPermissionRequestMarshaller_impl.hpp"
#endif
