#pragma once
#include "Amazon/Lambda/Model/Internal/MarshallTransformations/zzzz__UpdateFunctionEventInvokeConfigRequestMarshaller_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Amazon/Lambda/Model/Internal/MarshallTransformations/zzzz__UpdateFunctionEventInvokeConfigRequestMarshaller_impl.hpp"
#endif
