#pragma once
#include "Amazon/Lambda/Model/Internal/MarshallTransformations/zzzz__UpdateFunctionEventInvokeConfigResponseUnmarshaller_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Amazon/Lambda/Model/Internal/MarshallTransformations/zzzz__UpdateFunctionEventInvokeConfigResponseUnmarshaller_impl.hpp"
#endif
