#pragma once
#include "Amazon/DynamoDBv2/Model/zzzz__AutoScalingTargetTrackingScalingPolicyConfigurationDescription_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Amazon/DynamoDBv2/Model/zzzz__AutoScalingTargetTrackingScalingPolicyConfigurationDescription_impl.hpp"
#endif
