#pragma once
#include "Unity/Services/Vivox/zzzz__SWIGTYPE_p_f_p_void_p_q_const__char_p_q_const__char_p_short_int_int_int_int__void_def.hpp"
#ifndef CORDL_NO_IMPL_INCLUDE
#include "Unity/Services/Vivox/zzzz__SWIGTYPE_p_f_p_void_p_q_const__char_p_q_const__char_p_short_int_int_int_int__void_impl.hpp"
#endif
